apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: access-portal
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
# secret.example.yaml 仅作示例，不建议直接纳管真实密钥
